apiVersion: v1
kind: Service
metadata:
  name: key-value-store-api-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 30000
  selector:
    app: key-value-store-api
